name: 'Check'

on:
  workflow_dispatch:
  schedule:
  - cron:  '0 * * * *'

jobs:
  check:
    runs-on: self-hosted
    image: python:3.10
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install packages
      run: pip install requests selenium
    - name: Run script
      env:
      - TOKEN: ${{ secrets.TOKEN }}
      run: python3 steam.py
